import smtplib
from email.message import EmailMessage

email = EmailMessage()


email['from'] ='Pasindu Ukwatta'
#in this line add the recievers email address
email['to'] = ''
email['subject'] = 'Test Email Send from Python'

email.set_content('HI ! THIS IS A TEST PYTHON EMAIL GENRATED BY PYTHON CODING')

with smtplib.SMTP(host='smtp.gmail.com',port=587) as smtp:
    #starting the smtp 
    smtp.ehlo()
    #this is an encryption method
    smtp.starttls()
    
    #in this at first argument add the senders email address
    #second argument use the generated password from the two step authentication 
    smtp.login("sender email address","password generated by the two step authentication")
    smtp.send_message(email)
    print('all done')
    

