from twilio.rest import Client

account_sid = 'ACecba1d8d177ae38e5adc2430465a2a08'
auth_token = 'a9f3a1f0c10df7e67883b9e3e5fe3c07'
client = Client(account_sid, auth_token)

message = client.messages.create(
    from_='+16083735518',
    body='HI this is a Test SMS generated by Python ',
    to='+94712043390'
)

print(message.sid)