from twilio.rest import Client

account_sid = '######'
auth_token = 'Put the auth key here'
client = Client(account_sid, auth_token)

message = client.messages.create(
    from_='+1#######',
    body='HI this is a Test SMS generated by Python ',
    to='+947#######'
)

print(message.sid)
